config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :units do
    resources :models
    resources :equipment do
      resources :weapons do 
        resources :profiles
      end
    end
    resources :unit_abilities do 
      resources :abilities
    end
  end
  resources :factions
  resources :favorites

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get ":faction/info" => "factions#base", as: :base
  get ":faction/datasheets" => "factions#datasheets", as: :all
  get ":faction/datasheets/:type" => "factions#type", as: :type
  get ":username/favorite" => "favorites#mine", as: :my_favs
  post "favorite/new" => "favorites#create", as: :new_fav
 
  delete "delete_favorite/:id" => "favorites#destroy", as: :delete_favorite
  get "update_model/:unit_id/:id" =>"models#update", as: :update_model
  root "factions#home"
end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  before_action :set_faction, only: %i[ show edit update destroy ]
  before_action :authorize_user, except: [:home, :index, :base, :type, :datasheets]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # GET /factions or /factions.json
  def base 
    @faction = Faction.where(name: params[:faction]).last
  end
  def type
    @faction = Faction.where(name: params[:faction]).last
    @type = params[:type]
    @units = @faction.get_units_by_class(@type)
    @units.each do |unit|
      unit.favorites.build
    end

  end
  def index
    @factions = Faction.all
  end
  def datasheets
   @faction = Faction.where(name: params[:faction]).last
   @units = @faction.get_units
  end
  # GET /factions/1 or /factions/1.json
  def show
  end

  # GET /factions/new
  def new
    @faction = Faction.new
  end

  # GET /factions/1/edit
  def edit
  end

  # POST /factions or /factions.json
  def create
    @faction = Faction.new(faction_params)
    respond_to do |format|
      if @faction.save
        format.html { redirect_to faction_url(@faction), notice: "Faction was successfully created." }
        format.json { render :show, status: :created, location: @faction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factions/1 or /factions/1.json
  def update
    respond_to do |format|
      if @faction.update(faction_params)
        format.html { redirect_to faction_url(@faction), notice: "Faction was successfully updated." }
        format.json { render :show, status: :ok, location: @faction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1 or /factions/1.json
  def destroy
    @faction.destroy

    respond_to do |format|
      format.html { redirect_to factions_url, notice: "Faction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_faction
    @faction = Faction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def faction_params
    params.require(:faction).permit(:name, :banner, :icon, :picture)
  end

  def user_not_authorized
    flash[:alert] = "You aren't authorized for that"
    redirect_to(root_path)
  end

  def authorize_user
    if current_user
      authorize current_user
    else
      flash[:alert]= "You aren't authorized for that."
      redirect_back fallback_location: root_url
    end
  end
end

app/views/factions/_faction.html.erb
<div id="<%= dom_id faction %>">
  <p>
    <strong>Name:</strong>
    <%= faction.name %>
  </p>
  

</div>

app/views/factions/_form.html.erb
<%= form_with(model: faction) do |form| %>
  <% if faction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(faction.errors.count, "error") %> prohibited this faction from being saved:</h2>

      <ul>
        <% faction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :banner, style: "display: block" %>
    <%= form.text_field :banner %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/factions/base.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>
         <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Epic Hero</h5>
              <p class="card-text">Unique Characters in the setup every army can only have one at each</p>
              <button class="btn btn-primary">Epic Heros<%= link_to "Epic Heros",type_path(@faction.name, "epic hero"),faction: @faction, type: "epic hero" %></button>
            </div>
          </div>
      </td>
      <td>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Characters</h5>
              <p class="card-text">Characters fill the role of battlefield commanders some can lead units and an army can have three of each</p>
              <button class="btn btn-primary">Characters<%= link_to "Charaters",type_path(@faction.name, "character"),faction: @faction, type: "character" %></button>
            </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Battleline</h5>
              <p class="card-text">Standard rank and file troop, an army can have 6 of each unit</p>
              <button class="btn btn-primary">Battleline<%= link_to "Battleline",type_path(@faction.name, "battleline"),faction: @faction, type: "battleline" %></button>
            </div>
        </div>
      </td>
      <td>
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Transports</h5>
            <p class="card-text">Units that transport others in to combat, a army can only have 6 of each</p>
            <button class="btn btn-primary">Transport<%= link_to "Transport",type_path(@faction.name,"transport"),faction: @faction, type: "transport"  %></button>
          </div>
        </div>
      </td>
      <td>
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Other</h5>
            <p class="card-text">Armor, Specialists and other elite troops, an army can have 3 of each</p>
            <button class="btn btn-primary">Other<%= link_to "Other",type_path(@faction.name,"other"),faction: @faction, type: "other" %></button>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">All</h5>
            <p class="card-text">Show all units for this faction</p>
            <button class="btn btn-primary">All<%= link_to "All",all_path(@faction.name),faction: @faction  %></button>
          </div>
        </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/factions/datasheets.html.erb
<%@units.each do |unit|%>
  <%= render "units/unit_tab", unit: unit %>
<% end %>

app/views/factions/edit.html.erb
<h1>Editing faction</h1>

<%= render "form", faction: @faction %>

<br>

<div>
  <%= link_to "Show this faction", @faction %> |
  <%= link_to "Back to factions", factions_path %>
</div>

app/views/factions/home.html.erb
<h1>Welcome to Warhammer Army Checker</h2>
<% unit = Unit.new %>
<% unit = unit.get_one_eye%>
<%= render "units/unit_tab_home", unit: unit %> 

app/views/factions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Factions</h1>

<div id="factions">
  <% @factions.each do |faction| %>
    <%= render faction %>
    <p>
      <%= link_to "Show Units for this faction",base_path(faction.name),faction: faction  %>
    </p>
  <% end %>
</div>

app/views/factions/new.html.erb
<h1>New faction</h1>

<%= render "form", faction: @faction %>

<br>

<div>
  <%= link_to "Back to factions", factions_path %>
</div>

app/views/factions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @faction %>

<div>
  <%= link_to "Edit this faction", edit_faction_path(@faction) %> |
  <%= link_to "Back to factions", factions_path %>

  <%= button_to "Destroy this faction", @faction, method: :delete %>
</div>

app/views/factions/type.html.erb
<h1><%= @type.capitalize() %> for <%= @faction.name %></h1>
<ul class="list-group">
  <% @units.each do |unit| %>
  <li class="list-group-item">
    <%= render "units/unit_tab", unit: unit %>
  </li>
  <% end %>
</ul>