config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :units do
    resources :models
    resources :equipment do
      resources :weapons do 
        resources :profiles
      end
    end
    resources :unit_abilities do 
      resources :abilities
    end
  end
  resources :factions
  resources :favorites

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get ":faction/info" => "factions#base", as: :base
  get ":faction/datasheets" => "factions#datasheets", as: :all
  get ":faction/datasheets/:type" => "factions#type", as: :type
  get ":username/favorite" => "favorites#mine", as: :my_favs
  post "favorite/new" => "favorites#create", as: :new_fav
 
  delete "delete_favorite/:id" => "favorites#destroy", as: :delete_favorite
  get "update_model/:unit_id/:id" =>"models#update", as: :update_model
  root "factions#home"
end

app/models/weapon.rb
# == Schema Information
#
# Table name: weapons
#
#  id         :integer          not null, primary key
#  name       :string
#  range      :integer
#  skill      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Weapon < ApplicationRecord
  validates :name, uniqueness: { scope: [:range, :skill] }
  has_many :equipment, class_name: "Equipment", foreign_key: "weapon_id", dependent: :destroy
  has_many :profile
  def get_profiles 
     profile_array = Array.new 
      self.profile.each do |profile| 
        if !profile_array.include?(profile) 
          profile_array.push(profile) 
        end 
      end
      return profile_array
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: %i[ show edit update destroy ]
  before_action :authorize_user
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # GET /weapons or /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1 or /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new

  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons or /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)
    respond_to do |format|
      if @weapon.save
        format.html { redirect_to weapon_url(@weapon), notice: "Weapon was successfully created." }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1 or /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to weapon_url(@weapon), notice: "Weapon was successfully updated." }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1 or /weapons/1.json
  def destroy
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url, notice: "Weapon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end
    def set_equipment
      @equipment = Equipment.find(params[:equipment_id])
    end
    # Only allow a list of trusted parameters through.
    def weapon_params
      params.require(:weapon).permit(:name, :range)
    end
    def user_not_authorized
      flash[:alert] = "You aren't authorized for that"
      redirect_to(root_path)
    end
    def authorize_user
      if current_user
        authorize current_user
      else
        flash[:alert]= "You aren't authorized for that."
        redirect_back fallback_location: root_url
      end
    end
end

app/views/weapons/_form.html.erb
<%= form_with(model: weapon) do |form| %>
  <% if weapon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
        <% weapon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :range, style: "display: block" %>
    <%= form.number_field :range %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weapons/_weapon.html.erb
<div id="<%= dom_id weapon %>">
<% @profile_array = weapon.get_profiles%>
<% if @profile_array.length >= 2 %>
    <%= render "weapons/weapon_multiple", weapon: weapon%>
<% else %>
    <%= render "weapons/weapon_single", weapon: weapon, profile: @profile_array %>
<% end %>
</div>

app/views/weapons/_weapon_multiple.html.erb
<div id="<%= dom_id weapon %>">
    <div class="row border" >
      <p><%= weapon.name %></p>
    </div>
    <ul>
      <% weapon.profile.each do |profile|%>
      <li>
        <div class="row border" >
          <div class="col border">
            <%= profile.name%>
          </div>
          <div class="col-sm-2 border">
            <% if weapon.range === 0%>
              <p>Melee</p>
            <% else %>
              <p><%= weapon.range%></p>
            <% end %>
          </div>
          <div class="col border">
            <%= render "profiles/profile", profile: profile %>
          </div>
        </div>
      </li>
      <%end%>
    </ul>
</div>

app/views/weapons/_weapon_single.html.erb
<div id="<%= dom_id weapon %>">
  <div class="row border" >
    <div class="col border">
      <p><%= weapon.name %></p>
    </div>
    <div class="col-sm-2 border">
      <% if weapon.range === 0%>
        <p>Melee</p>
      <% else %>
        <p><%= weapon.range%></p>
      <% end %>
    </div>
    <div class="col border">
      <% profile.each do |p|%>
        <%= render "profiles/profile", profile: p %>
      <% end %>
    </div>
  </div>
</div>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Show this weapon", @weapon %> |
  <%= link_to "Back to weapons", weapons_path %>
</div>

app/views/weapons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weapons</h1>

<div id="weapons">
  <% @weapons.each do |weapon| %>
    <%= render weapon %>
    <p>
      <%= link_to "Show this weapon", weapon %>
    </p>
  <% end %>
</div>

<%= link_to "New weapon", new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Back to weapons", weapons_path %>
</div>

app/views/weapons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weapon %>

<div>
  <%= link_to "Edit this weapon", edit_weapon_path(@weapon) %> |
  <%= link_to "Back to weapons", weapons_path %>

  <%= button_to "Destroy this weapon", @weapon, method: :delete %>
</div>