config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :units do
    resources :models
    resources :equipment do
      resources :weapons do 
        resources :profiles
      end
    end
    resources :unit_abilities do 
      resources :abilities
    end
  end
  resources :factions
  resources :favorites

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get ":faction/info" => "factions#base", as: :base
  get ":faction/datasheets" => "factions#datasheets", as: :all
  get ":faction/datasheets/:type" => "factions#type", as: :type
  get ":username/favorite" => "favorites#mine", as: :my_favs
  post "favorite/new" => "favorites#create", as: :new_fav
 
  delete "delete_favorite/:id" => "favorites#destroy", as: :delete_favorite
  get "update_model/:unit_id/:id" =>"models#update", as: :update_model
  root "factions#home"
end

app/models/ability.rb
# == Schema Information
#
# Table name: abilities
#
#  id             :integer          not null, primary key
#  classification :string
#  description    :text
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Ability < ApplicationRecord
  validates :name, uniqueness: true
  has_many :unit_abilities
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :set_ability, only: %i[ show edit update destroy ]
  before_action :authorize_user
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # GET /abilities or /abilities.json
  def index
    @abilities = Ability.all
  end

  # GET /abilities/1 or /abilities/1.json
  def show
  end

  # GET /abilities/new
  def new
    @ability = Ability.new
  end

  # GET /abilities/1/edit
  def edit
  end

  # POST /abilities or /abilities.json
  def create
    @ability = Ability.new(ability_params)

    respond_to do |format|
      if @ability.save
        format.html { redirect_to ability_url(@ability), notice: "Ability was successfully created." }
        format.json { render :show, status: :created, location: @ability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abilities/1 or /abilities/1.json
  def update
    respond_to do |format|
      if @ability.update(ability_params)
        format.html { redirect_to ability_url(@ability), notice: "Ability was successfully updated." }
        format.json { render :show, status: :ok, location: @ability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1 or /abilities/1.json
  def destroy
    @ability.destroy
    respond_to do |format|
      format.html { redirect_to abilities_url, notice: "Ability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ability
      @ability = Ability.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def ability_params
      params.require(:ability).permit(:name, :description, :classification)
    end
    def user_not_authorized
      flash[:alert]
      redirect_to(home_path)
    end
    def authorize_user
      if current_user
        authorize current_user
      else
        flash[:alert]= "You aren't authorized for that."
        redirect_back fallback_location: root_url
      end
    end
end

app/views/abilities/_ability.html.erb
<div id="<%= dom_id ability %>">
  <p>
    <strong><%= ability.name %></strong>
  </p>
  <% if ability.description != nil %>
    <p>
      <%= ability.description %>
    </p>
  <%end%>


</div>

app/views/abilities/_form.html.erb
<%= form_with(model: ability) do |form| %>
  <% if ability.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
        <% ability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :classification, style: "display: block" %>
    <%= form.text_field :classification %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing ability</h1>

<%= render "form", ability: @ability %>

<br>

<div>
  <%= link_to "Show this ability", @ability %> |
  <%= link_to "Back to abilities", abilities_path %>
</div>

app/views/abilities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Abilities</h1>

<div id="abilities">
  <% @abilities.each do |ability| %>
    <%= render ability %>
    <p>
      <%= link_to "Show this ability", ability %>
    </p>
  <% end %>
</div>

<%= link_to "New ability", new_ability_path %>

app/views/abilities/new.html.erb
<h1>New ability</h1>

<%= render "form", ability: @ability %>

<br>

<div>
  <%= link_to "Back to abilities", abilities_path %>
</div>

app/views/abilities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ability %>

<div>
  <%= link_to "Edit this ability", edit_ability_path(@ability) %> |
  <%= link_to "Back to abilities", abilities_path %>

  <%= button_to "Destroy this ability", @ability, method: :delete %>
</div>