config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :units do
    resources :models
    resources :equipment do
      resources :weapons do 
        resources :profiles
      end
    end
    resources :unit_abilities do 
      resources :abilities
    end
  end
  resources :factions
  resources :favorites

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get ":faction/info" => "factions#base", as: :base
  get ":faction/datasheets" => "factions#datasheets", as: :all
  get ":faction/datasheets/:type" => "factions#type", as: :type
  get ":username/favorite" => "favorites#mine", as: :my_favs
  post "favorite/new" => "favorites#create", as: :new_fav
 
  delete "delete_favorite/:id" => "favorites#destroy", as: :delete_favorite
  get "update_model/:unit_id/:id" =>"models#update", as: :update_model
  root "factions#home"
end

app/models/unit.rb
# == Schema Information
#
# Table name: units
#
#  id              :integer          not null, primary key
#  base_size       :string
#  captain         :boolean
#  cost            :integer
#  damage          :boolean
#  dmg_amount      :integer
#  max_size        :integer
#  min_size        :integer
#  models_per_unit :integer
#  name            :string
#  picture         :string
#  role            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  faction_id      :integer          not null
#
# Indexes
#
#  index_units_on_faction_id  (faction_id)
#
class Unit < ApplicationRecord
  validates :name, uniqueness: true
  belongs_to :faction, class_name: "Faction"
  has_many :models, class_name: "Model"
  has_many :equipments, class_name: "Equipment"
  has_many :unit_abilities, class_name: "UnitAbility"
  has_many  :favorites, class_name: "Favorite", foreign_key: "unit_id", dependent: :destroy
  accepts_nested_attributes_for :favorites, allow_destroy: true

  def get_weapons
    # needs to get models and then their weapons and filter out the ones that are duplicates
    range_weapons = Array.new
    melee_weapons = Array.new
    self.equipments.each do |equipment|
      weapon = Weapon.where(id: equipment.weapon_id).last
        if !melee_weapons.include?(weapon) && weapon.range === 0
          melee_weapons.push(weapon)
        elsif !range_weapons.include?(weapon)&& weapon.range != 0
          range_weapons.push(weapon)
        end
    end
    weapons = Array.new
    if range_weapons.length != 0
      weapons.push(range_weapons)
    end
    weapons.push(melee_weapons)
    return weapons
  end
  def get_one_eye
    ooe = Unit.where(name: "Old One Eye").last
    return ooe
  end
  def get_abilities (type)
    unit_abilities = self.unit_abilities
    puts unit_abilities.class
    abilities = Array.new
    unit_abilities.each do |unit_ability|
      ability = Ability.where(id: unit_ability.ability_id).last
      if ability.classification === type
        abilities.push(ability)
      end
    end
    return abilities
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]
  before_action :authorize_user, except: [:show]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  #before_action :unit_pundit, only: [:show, :create, :update]
  # GET /units or /units.json
  def index
    @units = Unit.all
    
  end

  # GET /units/1 or /units/1.json
  def show
    @unit = Unit.find(name: params.fetch(:id))
    
    format.js do
      render template: "units/unit.js.erb"
    end
    #puts "#{@unit.name}"
  end
  def show 
    @unit = Unit.find(params.fetch(:id))
  end
  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.where(params.fetch("id")).first
    if authorize current_user, @unit
    else
      redirect_to units_url, notice: "Unit was successfully destroyed."
    end
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    authorize @unit
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end
    def user_not_authorized
      flash[:alert] = "You aren't authorized for that"
      redirect_to(root_path)
    end
    def authorize_user
      if current_user
        authorize current_user
      else
        flash[:alert]= "You aren't authorized for that."
        redirect_back fallback_location: root_url
      end
    end
    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:id, :name, :role, :cost, :faction_id, :max_size, :base_size, :picture)
    end

end

app/views/units/_ability.html.erb
<div id="<%= dom_id unit %>">
  <% if unit.get_abilities("CORE").length != 0 %>
    <div class="row border" >
      <div class= "col border">
        <p>Core:</p>
      </div>
        <% unit.get_abilities("CORE").each do |ability| %>
          <div class= "col border">
            <p><%= ability.name %></p>
          </div>
        <% end %>
    </div>
  <% end %>
  <% if unit.get_abilities("FACTION").length != 0 %>
    <div class="row border" >
      <div class="col border">
        <p>Faction:</p>
      </div>
        <% unit.get_abilities("FACTION").each do |ability| %>
          <div class= "col border">
            <p><%= ability.name %></p>
          </div>
        <% end %>
    </div>
  <% end %>
  <% if unit.get_abilities("STANDARD").length != 0 %>
    <div class="row border" >
      <ul class= "list-group">
        <% unit.get_abilities("STANDARD").each do |ability| %>
            <li class="list-group-item">
                <%= render "abilities/ability", ability: ability%>
            </li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <% if unit.get_abilities("WARGEAR").length != 0 %>
    <div class="row border" >
      <ul class= "list-group">
        <% unit.get_abilities("WARGEAR").each do |ability| %>
            <li class="list-group-item">
                <%= render "abilities/ability", ability: ability%>
            </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/units/_delete.html.erb
<div id="<%= dom_id unit %>_fav">
  <%= form_with(url: new_fav_path, data: { turbo: false }) do %>
    <input type="integer" id="unit" name="query_unit_id" value="<%= unit.id %>">
    <input type="integer" id="user" name="query_user_id" value="<%= current_user.id %>">
    <button>Favorite</button>
  <% end %>
</div>

app/views/units/_favorite.html.erb
<div id="<%= dom_id unit %>_fav">
  <div class="d-flex align-items-right">
    <% if current_user%>
      <% fav = current_user.favorites.find_by(unit: unit)%>
      <% if fav %> 
          <%= link_to delete_favorite_path(fav), method: :delete, class: "btn btn-primary", remote: false do %>
              <i class="fa-regular fa-star fa-xl"></i>
              
              <input type="hidden" id="unit" name="query_unit_id" value="<%= unit.id %>">
              <input type="hidden" id="user" name="query_user_id" value="<%= current_user.id %>">
            <% end %>

      <% else %>
        <%= render "favorites/form", unit: unit%>
      <% end %>
    <% end %>
  </div>

</div>

app/views/units/_form.html.erb
  <%= form_with(model: unit, url: unit_path(@unit), method: :patch, data: { turbo: false }) do |form| %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, value: "#{@unit.name}" %>
    </div>

    <div>
      <%= form.label :role, style: "display: block" %>
      <%= form.text_field :role, value: "#{@unit.role}" %>
    </div>

    <div>
      <%= form.label :cost, style: "display: block" %>
      <%= form.number_field :cost, value: "#{@unit.cost}" %>
    </div>

    <div>
      <%= form.label :max_size, style: "display: block" %>
      <%= form.number_field :max_size, value: "#{@unit.max_size}" %>
    </div>

    <div>
      <%= form.label :base_size, style: "display: block" %>
      <%= form.number_field :base_size, value: "#{@unit.base_size}" %>
    </div>

    <div>
      <%= form.label :picture, style: "display: block" %>
      <%= form.text_field :picture, value: "#{@unit.picture}" %>
    </div>
    <div>
      <%= form.label :faction_id, style: "display: block" %>
      <%= form.number_field :faction_id, value:"#{@unit.faction_id}" %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  <div>
      <% @unit.models.each do |model|%>
        <%= link_to model.name, unit_model_path(@unit.id, model), remote: false %>
      <% end %>
  </div>

app/views/units/_stats.html.erb
<div id="<%= dom_id unit %>">
  <div class= "row text-left border">
    <p><%= unit.name %></p>
  </div>
  <table class="table">
    <thead>
      <tr>
        <% if unit.models[0].name != unit.name %>
          <th scope="col">
            <strong>Name:</strong>
          </th>
        <% end%>
        <th scope="col">
          <p><strong>M</strong></p>
        </th>
        <th scope="col">
          <p><strong>T</strong></p>
        </th>
        <th scope="col">
          <p><strong>SV</strong></p>
        </th>
        <% if unit.models[0].invulnerable_save  != 0%>
          <th scope="col">
            <strong>Invulnerable Save</strong>
          </th>
        <% end%>
        <th scope="col">
          <p><strong>W</strong></p>
        </th>
        <th scope="col">
          <p><strong>LD</strong></p>
        </th>
        <th scope="col">
          <p><strong>OC</strong></p>
        </th>
      </tr>
    </thead>
    <tbody>
    <%# draws all models for a unit, i dont think i can move it to a render and maintain the format I want %>
      <% unit.models.each do |model| %>
        <tr>
          <% if model.name  != model.unit.name%>
            <td>
              <%= model.name%>
            </td>
          <% end%>
          <td>
            <%= model.movement %>
          </td>
          <td>
            <%= model.toughness %>
          </td>
          <td>
            <%= model.save_value %>
          </td>
          <% if model.invulnerable_save  != 0%>
            <td>
                <%= model.invulnerable_save%>
            </td>
          <% end%>
          <td>
            <%= model.wounds %>
          </td>
          <td>
            <%= model.leadership %>
          </td>
          <td>
            <%= model.objective_control %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <div class="container border">
    <div class="row border">
      <div class="col border">
          <%= render "units/stats", unit: unit%>
      </div>
    </div>
    <div class= "row border">
      <div class= "col border">
          <%= render "units/weapons", unit: unit%>
      </div>
      <div class="col border">
        <p>Abilities</p>
          <%= render"units/ability",unit: unit %>
      </div>
    </div>
  </div>
</div>

app/views/units/_unit_old.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Name:</strong>
    <%= unit.name %>
  </p>

  <% if unit.role != nil%>
    <p>
      <strong>Role:</strong>
      <%= unit.role %>
    </p>
  <%end%>
  <p>
    <strong>Cost:</strong>
    <%= unit.cost %>
  </p>

  <p>
    <strong>Faction:</strong>
    <%= Faction.where(id: unit.faction_id).last.name %>
  </p>

  <p>
    <strong>Max size:</strong>
    <%= unit.max_size %>
  </p>

  <p>
    <strong>Base size:</strong>
    <%= unit.base_size %>
  </p>

 <% if unit.picture != nil%>
  <p>
    <strong>Picture:</strong>
    <%= unit.picture %>
  </p>
  <%end%>
  <%# gets models %>
  <% unit.models.each do |model| %>
    <%= render "models/model", model: model %>
  <% end %>
<%# gets weapons %>
<div class="container text-center">
  <% unit.models.each do |model| %>
    <% melee = Array.new %>
    <% range = Array.new %>
    <% model.equipments.each do |equipment| %>
      <% if(equipment.weapon.range == 0)%>
        <% melee.push(equipment) %>
      <% else %>
        <% range.push(equipment)%>
      <% end %>
    <% end %>
    <%if range.length == 0 %>
      <div class="row">
        <% melee.each do |equipment|%>
        <%= render "equipments/equipment", equipment: equipment %>
        <% end %>
      </div>
    <%else%>
        <div class="row">
          <div class="col">
            Ranged Weapons
          </div>
          <div class="col">
            Range
          </div>
          <div class="col">
            Attacks
          </div>
          <div class="col" >
            Balistic Skill
          </div>
          <div class="col">
            Strength
          </div>
          <div class="col">
            Armor Piercing
          </div>
          <div class="col">
            Damage
          </div>
        </div>
       <div class="row">
          <% range.each do |equipment|%>
            <div class="row">
              <%= render "units/stats", equipment: equipment %>
            </div>
          <% end %>
        </div>
        <div class="row">
        <% melee.each do |equipment|%>
        <%= render "equipments/equipment", equipment: equipment %>
        <% end %>
        
    <% end %>
  <% end %>
  </div>
  <%# if this logic is not being used anymore, you should delete this commented code and refer to comments for explanation instead =%>

  <%# This following block works on collecting all weapons for a model %>
  <%# unit.models.each do |model| %>
    <%# model.equipments.each do |equipment| %>
      <%#= render "equipments/equipment", equipment: equipment %>
    <%# end %>
  <%# end %>

  <div class="container text-center">
    <div class="row">
    <%# range weapons %>
      <div class="col">
        Ranged Weapons
      </div>
      <div class="col">
        Range
      </div>
      <div class="col">
        Attacks
      </div>
      <div class="col" >
        Balistic Skill
      </div>
      <div class="col">
        Strength
      </div>
      <div class="col">
        Armor Piercing
      </div>
      <div class="col">
        Damage
      </div>
    </div>
      <div class="row">
    <%# Melee weapons %>
      <div class="col">
        Melee Weapons
      </div>
      <div class="col">
        Range
      </div>
      <div class="col">
        Attacks
      </div>
      <div class="col" >
        Weapons Skill
      </div>
      <div class="col">
        Strength
      </div>
      <div class="col">
        Armor Piercing
      </div>
      <div class="col">
        Damage
      </div>
    </div>
  </div>



</div>

app/views/units/_unit_tab_home.erb
<div id="<%= dom_id unit %>">
   <div class= "container border">
      <div class="row border">
         <div class= "col ">
            <ul class="list-group">
               <li class="list-group-item" id="list_<%= dom_id unit%>"><%= unit.name %><%= unit.base_size%>
               </li>
               <li class="list-group-item">
                <p> 
                <%= button_to root_path, method: :get, class: "btn btn-primary" do %>
               <i class="fa-solid fa-star fa-xl"></i>
               <% end %>
                  Click this button to favorite/unfavorite units if signed in
                </p>
               </li>
            </ul>
         </div>

         <div class= "col ">
               <%= image_tag(unit.picture)%>
         </div>
      </div>

      <div class="row border align-items-center">
         <div class="col justify-content-md-center">
            <div>
              <p>             
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#<%= unit.id %>" aria-expanded="false" aria-controls="collapseExample">
                          <svg xmlns="http://www.w3.org/2000/svg" width="100" height="20" fill="currentColor" class="bi bi-arrow-bar-down align-items-center" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 3.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5M8 6a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 .708-.708L7.5 12.293V6.5A.5.5 0 0 1 8 6"/>
                          </svg>
                </button>
                Click this button to display the units information
              </p>
               <div class="collapse" id= "<%= unit.id %>">
                  <div class="card card-body">
                     <%= render "units/unit", unit: unit  %>
                  </div>
               </div>
            </div>
         </div>

         </div>
      </div>
   </div>
</div>

app/views/units/_weapons.html.erb
<div id="<%= dom_id unit %>">
<%  weapons = unit.get_weapons %>
    <%# Shows melee weapons and range weapons if they exist %>
      <% weapons.each do |type| %>
        <% if type[0] %>
          <table class="table">
            <thead>
              <tr>
                <% if type[0].range != 0 %>
                  <th>Range Weapons:</th>
                <% else %>
                  <th>Melee Weapons:</th>
                <% end %>
                <th>Range: </th>
                <th>A</th>
                <% if type[0].range != 0 %>
                  <th>BS</th>
                <% else %>
                  <th>AS</th>
                <% end %>
                <th>S</th>
                <th>AP</th>
                <th>Damage</th>
              </tr>
            </thead>
            <tbody>
              <% type.each do |weapon| %>
                <tr>
                  <td><%= weapon.name%></td>
                  <% if weapon.profile.length > 1 %>
                    </tr>

                    <% weapon.profile.each do |profile|%>
                      <tr>
                      <td>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
                        </svg>
                      <%= profile.name %></td>
                      <td>
                      <% if weapon.range === 0%>
                      Melee
                      <% else %>
                      <%= weapon.range %>
                      <% end %>
                      </td>
                      <td><%= profile.attacks%></td>
                      <td><%= profile.skill%></td>
                      <td><%= profile.strength%></td>
                      <td><%= profile.armor_piercing%></td>
                      <td><%= profile.damage%></td>
                      </tr>
                    <% end %>
                  <% else %>
                  <td>
                    <% if weapon.range === 0%>
                    Melee
                    <% else %>
                    <%= weapon.range %>
                    <% end %>
                    </td>
                    <% if weapon.profile.last%>
                      <td><%= weapon.profile.last.attacks%></td>
                      <td><%= weapon.profile.last.skill%></td>
                      <td><%= weapon.profile.last.strength%></td>
                      <td><%= weapon.profile.last.armor_piercing%></td>
                      <td><%= weapon.profile.last.damage%></td>
                      <%else%>
                      <td>not found</td>
                      <td>not found</td>
                      <td>not found</td>
                      <td>not found</td>
                      <td>not found</td>
                      <%end%>
                  <% end %>
                </tr> 
              <% end %>
            </tbody>
          </table>
          <%end%>
      <% end%>
</div>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Show this unit", @unit %> |
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Units</h1>

<div id="units">
  <% @units.each do |unit| %>
    <%= render unit %>
    <p>
      <%= link_to "Show this unit", unit %>
    </p>
  <% end %>
</div>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Back to units", unit_path %>
</div>

app/views/units/soon.html.erb
<p>Coming Soon</p>

app/views/units/unit.js.erb
console.log("bye comment!")